export const MOVE_TICKET = 'MOVE_TICKET';
export const RESET_TICKETS = 'RESET_TICKETS';
export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';
export const RECEIVE_TICKETS_ERROR = 'RECEIVE_TICKETS_ERROR';
export const SAVE_TICKETS = 'SAVE_TICKETS';

/*export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const RECEIVE_PROJECTS_ERROR = 'RECEIVE_PROJECTS_ERROR';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';*/

export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export const RESET_USER = 'RESET_USER';

export const SHOW_SIDE_MENU = 'SHOW_SIDE_MENU';
export const HIDE_SIDE_MENU = 'HIDE_SIDE_MENU';

export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM';
export const OPEN_ITEM_CARD = 'OPEN_ITEM_CARD';
export const CLOSE_ITEM_CARD = 'CLOSE_ITEM_CARD';

export const UPDATE_DEADLINE = 'UPDATE_DEADLINE';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_PRIORITY = 'UPDATE_PRIORITY';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';

export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const RECEIVE_PROJECTS_ERROR = 'RECEIVE_PROJECTS_ERROR';

export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';
