export const MOVE_TICKET = 'MOVE_TICKET';
export const RESET_TICKETS = 'RESET_TICKETS';
export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';
export const RECEIVE_TICKETS_ERROR = 'RECEIVE_TICKETS_ERROR';
export const SAVE_TICKETS = 'SAVE_TICKETS';

export const REQUEST_TICKET_SAVE = 'REQUEST_TICKET_SAVE';

/*export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const RECEIVE_PROJECTS_ERROR = 'RECEIVE_PROJECTS_ERROR';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';*/

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const RECEIVE_USER_LOGIN_ERROR = 'RECEIVE_USER_LOGIN_ERROR';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export const RESET_USER_LOGIN = 'RESET_USER_LOGIN';

export const REQUEST_USER_REGISTRATION = 'REQUEST_USER_REGISTRATION';
export const RECEIVE_USER_REGISTRATION_ERROR = 'RECEIVE_USER_REGISTRATION_ERROR';

export const SHOW_SIDE_MENU = 'SHOW_SIDE_MENU';
export const HIDE_SIDE_MENU = 'HIDE_SIDE_MENU';

export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM';
export const OPEN_ITEM_CARD = 'OPEN_ITEM_CARD';
export const CLOSE_ITEM_CARD = 'CLOSE_ITEM_CARD';

export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const RECEIVE_PROJECTS_ERROR = 'RECEIVE_PROJECTS_ERROR';

export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';

export const CHANGE_ASSIGNEE_FILTER = 'CHANGE_ASSIGNEE_FILTER';
