export const MOVE_TICKET = 'MOVE_TICKET';
export const RESET_TICKETS = 'RESET_TICKETS';
export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';
export const RECEIVE_TICKETS_ERROR = 'RECEIVE_TICKETS_ERROR';
export const SAVE_TICKETS = 'SAVE_TICKETS';

/*export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const RECEIVE_PROJECTS_ERROR = 'RECEIVE_PROJECTS_ERROR';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';*/

export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export const RESET_USER = 'RESET_USER';
